
include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    combinators_ordering: ignore
    depend_on_referenced_packages: ignore
    invalid_annotation_target: ignore
    no_default_cases: ignore
  exclude:
    - lib/l10n/generated/*
    - lib/generated/*
    - lib/**/*.g.dart
    - lib/**.freezed.dart
    - lib/**.gr.dart
    - assets/**/*.gen.dart
    - lib/**/*.gen.dart
    - test/mocks/**.mocks.dart
linter:

  rules:
